
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED'

export const ADMIN_REGISTER_REQUEST = 'ADMIN_REGISTER_REQUEST'
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS'
export const ADMIN_REGISTER_FAILED = 'ADMIN_REGISTER_FAILED'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE"

export const UPDATE_SETTING_REQUEST = "UPDATE_SETTING_REQUEST"
export const UPDATE_SETTING_SUCCESS = "UPDATE_SETTING_SUCCESS"
export const UPDATE_SETTING_FAILURE = "UPDATE_SETTING_FAILURE"

export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAILURE = "GET_USER_FAILURE"

export const APPLY_SME_LOAN_REQUEST = 'APPLY_SME_LOAN_REQUEST'
export const APPLY_SME_LOAN_SUCCESS = 'APPLY_SME_LOAN_SUCCESS'
export const APPLY_SME_LOAN_FAILURE = 'APPLY_SME_LOAN_FAILURE'

export const APPLY_PAYDAY_LOAN_REQUEST = 'APPLY_PAYDAY_LOAN_REQUEST'
export const APPLY_PAYDAY_LOAN_SUCCESS = 'APPLY_PAYDAY_LOAN_SUCCESS'
export const APPLY_PAYDAY_LOAN_FAILURE = 'APPLY_PAYDAY_LOAN_FAILURE'

export const FETCH_USER_SELECTED_SME_LOAN_REQUEST = 'FETCH_USER_SELECTED_SME_LOAN_REQUEST'
export const FETCH_USER_SELECTED_SME_LOAN_SUCCESS = 'FETCH_USER_SELECTED_SME_LOAN_SUCCESS'
export const FETCH_USER_SELECTED_SME_LOAN_FAILURE = 'FETCH_USER_SELECTED_SME_LOAN_FAILURE'

export const FETCH_USER_SELECTED_PAYDAY_LOAN_REQUEST = 'FETCH_USER_SELECTED_PAYDAY_LOAN_REQUEST'
export const FETCH_USER_SELECTED_PAYDAY_LOAN_SUCCESS = 'FETCH_USER_SELECTED_PAYDAY_LOAN_SUCCESS'
export const FETCH_USER_SELECTED_PAYDAY_LOAN_FAILURE = 'FETCH_USER_SELECTED_PAYDAY_LOAN_FAILURE'


export const FETCH_USER_PAYDAY_LOAN_SUCCESS = 'FETCH_USER_PAYDAY_LOAN_SUCCESS'
export const FETCH_USER_PAYDAY_LOAN_FAILURE = 'FETCH_USER_PAYDAY_LOAN_FAILURE'

export const FETCH_USER_LOANS_REQUEST = 'FETCH_USER_LOANS_REQUEST'

export const FETCH_USER_SME_LOAN_SUCCESS = 'FETCH_USER_SME_LOAN_SUCCESS'
export const FETCH_USER_SME_LOAN_FAILURE = 'FETCH_USER_SME_LOAN_FAILURE'

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'

export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const HIDE_MESSAGE = 'HIDE_MESSAGE'



