export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE"

export const UPDATE_SETTING_REQUEST = "UPDATE_SETTING_REQUEST"
export const UPDATE_SETTING_SUCCESS = "UPDATE_SETTING_SUCCESS"
export const UPDATE_SETTING_FAILURE = "UPDATE_SETTING_FAILURE"