export const LOGIN_ENDPOINT = "/auth/login"
export const REGISTER_ENDPOINT = "/auth/register"
export const CHANGE_PASSWORD_ENDPOINT = "/auth/changepassword/"
export const GET_USER_ENDPOINT = "/user/"
export const SME_LOAN_ENDPOINT = "/user/createSMEloan"
export const PAYDAY_LOAN_ENDPOINT = "/user/createpaydayloan"